CREATE DATABASE NETFLIX;
USE NETFLIX;

CREATE TABLE NUMERO(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	NUMERO VARCHAR(50),
	DESCRICAO VARCHAR(250),
	CONSTRAINT PK_NUMERO PRIMARY KEY(ID)
);
GO

CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	NOME VARCHAR(50),
	EMAIL VARCHAR(100),
	ID_NUMERO INT NOT NULL
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
	CONSTRAINT FK_NUMERO FOREIGN KEY (ID_NUMERO) REFERENCES DBO.NUMERO(ID),
);
GO

CREATE TABLE CONTA(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	DESCRICAO VARCHAR(50),
	CONSTRAINT PK_CONTA PRIMARY KEY(ID),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(ID) REFERENCES DBO.CLIENTE(ID),
);
GO

CREATE TABLE FORMA_DE_PAGAMENTO(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	DESCRICAO VARCHAR(250),
	CONSTRAINT PK_FORMA_DE_PAGAMENTO PRIMARY KEY(ID),
);
GO

CREATE TABLE PLANOS(
	ID INT IDENTITY(1,1) NOT NULL, -- AUTO INCREMENTO
	QUANT_TELAS CHAR(4),
	DESCRICAO VARCHAR(250),
	CONSTRAINT PK_PLANOS PRIMARY KEY(ID),
	CONSTRAINT FK_FORMA_DE_PAGAMENTO FOREIGN KEY(ID) REFERENCES DBO.FORMA_DE_PAGAMENTO(ID),
);
GO